name: CI - UserService

on:
  push:
    paths:
      - 'services/UserService/**'
    branches:
      - main
  pull_request:
    paths:
      - 'services/UserService/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.308'

      # 3. Restore solution
      - name: Restore dependencies
        run: dotnet restore services/UserService/UserService.sln

      # 4. Build solution
      - name: Build
        run: dotnet build services/UserService/UserService.sln --no-restore --configuration Release

      # 5. Run tests
      - name: Run tests
        run: dotnet test services/UserService/TestUser/TestUser.csproj --no-build --verbosity normal
